import test from 'node:test';
import assert from 'node:assert/strict';
import {RescueGame,seededRandom,returnValue} from '../src/engine.js';
import {stage} from '../src/stage.js';
const make=()=>{const g=new RescueGame(stage,seededRandom(7));g.start();return g;};
const advance=(g,s)=>{for(let i=0;i<s*120;i++)g.update(1/120);};
test('without input gravity pulls the player down',()=>{const g=make(),y=g.player.y;advance(g,.35);assert.ok(g.player.y>y+30);assert.ok(g.player.vy>200);});
test('right tap immediately rises; holding does not repeat; later falls',()=>{const g=make();g.player.y=650;g.flap();assert.equal(g.player.vy,-330);advance(g,.2);assert.ok(g.player.y<610);advance(g,.35);assert.ok(g.player.vy>0);});
test('left/right steering is independent of vertical lift',()=>{const g=make();g.setDirection(-1);g.flap();advance(g,.2);assert.ok(g.player.vx<0);assert.ok(g.player.vy<0);g.setDirection(1);advance(g,.3);assert.ok(g.player.vx>0);assert.equal(g.direction,1);g.flap();assert.equal(g.direction,1);g.setDirection(0);advance(g,.2);assert.ok(g.player.vx>0);});
test('world extends beyond old room bounds, with more HOME points',()=>{const g=make();g.player.x=2500;g.world.extend(g);assert.ok(g.world.next>=4);assert.ok(g.homes.some(h=>h.x>3000));assert.ok(g.friends.some(f=>f.x>3000));});
test('ten minute unobstructed flight has no time limit and bounded live geometry',()=>{const g=make();const extend=g.world.extend.bind(g.world);let homes=g.homes;g.world.extend=game=>{game.homes=homes;extend(game);homes=game.homes;game.homes=[];};g.cooldown=10000;g.setDirection(1);for(let i=0;i<600*120;i++){for(const o of g.obstacles)o.disabled=1;if(g.player.y>640&&g.player.vy>0)g.flap();g.update(1/120);g.drain();}assert.equal(g.state,'playing');assert.ok(g.time>599);assert.ok(g.player.x>100000);assert.ok(g.obstacles.length<=168);assert.ok(g.stage.props.length<=72);assert.ok(g.homes.length<=12);});
test('rescue remains unbanked until HOME and counts each delivery exactly once',()=>{const g=make();for(const f of g.friends.slice(0,5))g.rescue(f);const value=returnValue(g.carry).reduce((a,b)=>a+b,0);assert.equal(g.score,0);g.beginReturn();const home={...g.returnHome};g.stage.home={x:5000,y:790};while(g.bankQueue.length)g.bankOne();assert.equal(g.score,value);assert.equal(g.rescued,5);assert.equal(g.returnCheckpoint.attached.length,5);assert.ok(g.drain().filter(e=>e.type==='bank').every(e=>Math.abs(e.homeX-home.x)<140));});
test('collision protection and tail loss still work',()=>{const g=make();g.rescue(g.friends[0]);g.hit();assert.equal(g.carry.length,0);g.time=31;assert.equal(g.hearts,3);g.cooldown=0;g.hit();assert.equal(g.hearts,2);});
test('retry resets distance, chunks, input, life and scores',()=>{const g=make();g.player.x=6000;g.world.extend(g);g.setDirection(-1);g.score=1200;g.start();assert.equal(g.score,0);assert.equal(g.travel,0);assert.equal(g.direction,0);assert.equal(g.hearts,3);assert.equal(g.player.x,205);assert.ok(g.world.next<=3);});

test("neutral flight flows forward at the tuned cruising speed",()=>{const g=make(),x=g.player.x;g.player.y=200;advance(g,1);assert.ok(g.player.x-x>175);assert.ok(g.player.vx>=189);});

test('falling has no floor, camera neighborhood continues at depth',()=>{const g=make();g.player.y=5000;g.world.extend(g);g.obstacles=[];const y=g.player.y;advance(g,1);assert.ok(g.player.y>y+300);assert.ok(g.homes.some(h=>h.y>5000));assert.ok(g.friends.some(f=>f.y>5000));});
test('eight friends surround the hero instead of trailing in a line',()=>{const g=make();for(const f of g.friends.slice(0,8))g.rescue(f);g.obstacles=[];g.friends=[];advance(g,.4);assert.ok(g.carry.some(f=>f.x>g.player.x+20));assert.ok(g.carry.some(f=>f.x<g.player.x-20));assert.ok(g.carry.some(f=>f.y>g.player.y+20));assert.ok(g.carry.some(f=>f.y<g.player.y-20));});
test('world objects and unrescued friends move from the start',()=>{const g=make(),f=g.friends[8],o={x:600,y:250,baseX:600,baseY:250,r:20,phase:0,disabled:0},prop=g.homes[0];g.obstacles.push(o);const start=[f,o,prop].map(p=>({x:p.x,y:p.y}));advance(g,.5);for(const [i,p] of [f,o,prop].entries())assert.ok(Math.hypot(p.x-start[i].x,p.y-start[i].y)>1);});
test('obstacle collision removes two attached friends even during opening protection',()=>{const g=make();g.world.extend=()=>{};for(const f of g.friends.slice(0,8))g.rescue(f);g.friends=[];g.homes=[];const p=g.player;g.obstacles=[{x:p.x,y:p.y,baseX:p.x,baseY:p.y,r:30,phase:0,disabled:0}];g.update(1/120);assert.equal(g.carry.length,6);assert.equal(g.hearts,3);g.hit();assert.equal(g.carry.length,6);assert.ok(g.drain().some(e=>e.type==='lost'));});
test('the attached group settles into a tightly packed cluster',()=>{const g=make();g.world.extend=()=>{};g.obstacles=[];g.homes=[];for(const f of g.friends.slice(0,8))g.rescue(f);g.friends=[];advance(g,.7);assert.ok(g.carry.every(f=>Math.hypot(f.x-g.player.x,f.y-g.player.y)<60));});

test('section palette matches danger density and bonus rewards',()=>{const g=make();const count=k=>g.obstacles.filter(o=>o.chunk===k).length;assert.equal(g.obstacles.length,0);assert.ok(g.friends.filter(f=>f.chunk==='1:0'&&f.rare).length>g.friends.filter(f=>f.chunk==='0:0'&&f.rare).length);g.player.x=2800;g.world.extend(g);assert.equal(g.biome.id,'neon');g.player.y=1600;g.world.extend(g);assert.equal(g.biome.id,'sky');});

test('checkpoint scores only after crossing its opening',()=>{const g=make();g.world.extend=()=>{};g.incoming.update=()=>{};const h=g.homes[0];g.homes=[h];g.obstacles=[];g.player.x=h.x-35;g.player.y=h.y-25;g.rescue(g.friends[0]);g.friends=[];advance(g,.05);assert.equal(g.rescued,0);assert.equal(g.carry.length,1);advance(g,.25);assert.equal(g.carry.length,0);assert.equal(g.rescued,1);});
test('crossing beside the ring opening does not bank friends',()=>{const g=make();g.world.extend=()=>{};g.incoming.update=()=>{};const h=g.homes[0];g.homes=[h];g.obstacles=[];g.player.x=h.x-20;g.player.y=h.y+110;g.rescue(g.friends[0]);g.friends=[];advance(g,.2);assert.equal(g.carry.length,1);assert.equal(g.rescued,0);});
